apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-0oee
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-0oee
    app.kubernetes.io/part-of: tkrw-pr712-0075-0001-app
  name: devfile-sample-0oee
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-0oee
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-0oee
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0001-tenant/tkrw-pr712-0075-0001-app/devfile-sample-0oee@sha256:18110d6a1eee82d1fe4ca57cb262243a82a41285a9d200eb1b7414622d8f7ddd
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
